### ISSUE TITLE
邀请收录进： awesome-github-profile-readme-chinese

### ISSUE THREAD

**Issue by eryajf** [teamssix/teamssix#1]
你好，你的个人主页很赞，我做了一个中文区优秀个人主页合集的项目，特邀请你参与贡献。

项目地址：https://github.com/eryajf/awesome-github-profile-readme-chinese

**Comment by teamssix** [comment]
@eryajf 可以啊，非常荣幸，参与的方式是我给这个项目提交pr吗还是怎么操作？

**Comment by eryajf** [comment]
恩恩，走PR吧，这样你也会在贡献者列表中

**Comment by eryajf** [comment]
是的，走pr吧



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月02日 18:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [teamssix/teamssix] 邀请收录进： awesome-github-profile-readme-chinese (Issue #1) |

@eryajf 可以啊，非常荣幸，参与的方式是我给这个项目提交pr吗还是怎么操作？
